### Create
POST localhost:8080/api/v1/category
Content-Type: application/json

{
  "name": "fizika"
}

### Get All
GET localhost:8080/api/v1/category/get-all?page=0&size=5

### Get BY Id
GET localhost:8080/api/v1/category/090d6848-5275-4867-a8f9-21eea18c84b8


### Update (id, categoryCr)
PUT localhost:8080/api/v1/category/a3e67ef7-5f89-47c8-9574-814c2cabe07f
Content-Type: application/json

{
  "name": "erkaklar kiyimi"
}

### Delete By id
DELETE localhost:8080/api/v1/category/a3e67ef7-5f89-47c8-9574-814c2cabe07f
Authorization: Bearer