### Create Quiz
POST localhost:7070/api/v1/quiz/create
Content-Type: application/json

{
  "title": "Test Quiz",
  "description": "Bu test quiz uchun",
  "timeLimit": 30,
  "isPublished": false
}

### Get Quiz by ID
GET localhost:7070/api/v1/quiz/get-by-id/550e8400-e29b-41d4-a716-446655440000

### Get All Published Quizzes
GET localhost:7070/api/v1/quiz/published

### Update Quiz
PUT localhost:7070/api/v1/quiz/update/550e8400-e29b-41d4-a716-446655440000
Content-Type: application/json

{
  "title": "Yangilangan Quiz",
  "description": "Yangilangan tavsif",
  "timeLimit": 45,
  "isPublished": true
}

### Delete Quiz
DELETE localhost:7070/api/v1/quiz/delete/550e8400-e29b-41d4-a716-446655440000